### ISSUE TITLE
Add Review Page is broken/ not really good for what we need

### ISSUE THREAD

**Issue by Sjbrimley26** [chingu-voyage3/bears-13#32]
We need to incorporate the Review portion of the page into all the location pages so that once a user navigates to the location's page, they can add a review about the location.

**Comment by shoesandsocks** [comment]
I'm on this one now. Reworking Add Review as a subcomponent of a location's page.

**Comment by Sjbrimley26** [comment]
Perfect!

**Comment by shoesandsocks** [comment]
resolved by bugfix-40 merge
