### ISSUE TITLE
Flesh out the Profile Page

### ISSUE THREAD

**Issue by Sjbrimley26** [chingu-voyage3/bears-13#33]
We need to have options so the user can change their username/avatar and they should also be able to see the reviews that they have posted from their profile page.

**Comment by shoesandsocks** [comment]
@Sjbrimley26 could you open up `rework-initial-signup` and build an editProfile mutation when you get a chance?

**Comment by shoesandsocks** [comment]
see the Profile.js component, line 95, for how I think we want to use it -- although it should use `_id` not `auth_id` (that's a cut and paste error from where I copied that query from the createUser code on another page)

**Comment by shoesandsocks** [comment]
what else should be editable, here? contemplating a delete-review button on each review...

**Comment by Sjbrimley26** [comment]
That would be nice, I can't really think of anything else other than to delete the profile or like set background color or something weird like that. I'm adding the mutation now, though.

**Comment by shoesandsocks** [comment]
it actually wouldn't be crazy-hard to 'theme' the whole thing a little. that's knocking around in my head as part of a bigger visual re-do.

**Comment by shoesandsocks** [comment]
basics from this one done; will add new Issue re: general visual improvement
