### ISSUE TITLE
"You've already reviewed this location"

### ISSUE THREAD

**Issue by shoesandsocks** [chingu-voyage3/bears-13#37]
When there's already a review by the logged in user, what behavior? currently there's no check at all, you just keep adding reviews. that might be okay for an "MVP" but what's the preferred behavior? Offer to "edit/delete review"?

**Comment by Sjbrimley26** [comment]
Yeah the edit/delete makes more sense, I don't know anywhere that lets you have more than one review, but maybe we could let them do one a year or something?

**Comment by shoesandsocks** [comment]
that doesn't sound too hard on the front end... what are the back-end/graphQL implications of "edit review" and "delete review"? just more mutations to code up?

**Comment by Sjbrimley26** [comment]
Yup, should be easy-peasy

**Comment by nikw92** [comment]
1 review per user per property sounds good. Perhaps we could keep a review history like in Facebook comments. But this is something we can do in the future as it could definitely be harder.

**Comment by shoesandsocks** [comment]
closed by bugfix-37
