### ISSUE TITLE
Hosting app (heroku?)

### ISSUE THREAD

**Issue by shoesandsocks** [chingu-voyage3/bears-13#38]
I think we're very close to having something that could be merged into `master` and given a web address other than `localhost`.

Anyone have experience getting things up and running on, say, Heroku? I have gotten smaller projects on there, but not something with this level of scripting at the start. Does TravisCI somehow help us in that regard?

(bigger question: should we consider Docker? I was pair programming with someone a few months ago and he got me to install it, but i'll be damned if I understand it.)

**Comment by Sjbrimley26** [comment]
I don't know about Docker and I only have a couple small projects on Heroku, none where its running two apps, but I have used clustering on it and that worked fine. Travis just makes sure that the deploy on github passes all our specified tests before it gets to Heroku, that way if there is an error, it isn't deployed directly to your live Heroku site.
I think adding our build pack to Heroku will be the tricky part, if there is a tricky part.

**Comment by Sjbrimley26** [comment]
Gonna go ahead and close this one since we have it running on Heroku.
